### ISSUE TITLE
Session segmentation

### ISSUE THREAD

**Issue by dudaubogdan** [microsoft/clarity#109]
Our users frequently work with many open tabs in our app. The problem is that Clarity seems to register each tab as a different session, so we sometimes get 30 separate 1-minute recordings of a user instead of a single 30-minute session, which can be annoying.

Is there any solution for this?
Thanks,
Bogdan

**Comment by sarveshnagpal** [comment]
Thanks @dudaubogdan - Clarity uses session storage for session tracking and it is tab specific by design. I will track this as a feature request but one of the challenges with multiple tabs is overlapping visualization. Since multiple tabs could have multiple things going in parallel - it's hard to visualize on one timeline. If you have suggestions or expectations on how that would work - happy to add it to feature request notes. Thanks.

**Comment by dudaubogdan** [comment]
I've seen Hotjar handle multiple tabs pretty well. Not sure about the inner workings, but switching between tabs looks linear, just like regular navigation. By the looks of it, when activity is registered on another tab, it brings that screen into view and the change is labeled as "visiting a new page".

Thanks for your support, would be very cool to see this implemented at some point in the future.

**Comment by sarveshnagpal** [comment]
Following up. With #127 Clarity moved to using session cookies from session storage to address this. The issue is resolved now.
