### ISSUE TITLE
salesforce chatbot conflict

### ISSUE THREAD

**Issue by DamonDay** [microsoft/clarity#192]
abnormal chatbot screenshot (with MS Clarity integrated)
![image](https://user-images.githubusercontent.com/24534739/141253104-1bd75971-8302-4063-9791-6fcf9448f281.png)

normal (MS Clarity disabled)
![image](https://user-images.githubusercontent.com/24534739/141255084-c1d8226a-2c93-4558-9ab4-027cdf6507f1.png)

the official document of salesforce chatbot: https://www.salesforce.com/products/service-cloud/features/live-agent/

**Comment by bakervin** [comment]
We are having the same issue, but have noticed this actually with Salesforce Snapins Chat, not necessarily Chatbots.  We have since disabled Clarity due to the broken CSS with Salesforce Chat

**Comment by pmdartus** [comment]
Spent some time investigating this issue today. Here is the summary.

**Repro steps:**

This issue only occurs when the scripts are loaded and executed in this order first Clarity and then Salesforce chatbot. Unfortunately, I can't share any live environment showcasing this issue.

**Root cause analysis:**

The way `attachShadow` is patched by Clarity is incompatible with the way Salesforce Lightning Web Component (LWC) patches the same API. 

Clarity patches `attachShadow` on the `HTMLElement.prototype` ([code](https://github.com/microsoft/clarity/blob/a9eea076a8b7566d6803d7f0c67e510fc21979e5/packages/clarity-js/src/layout/mutation.ts#L59-L61)), while LWC patches the same API on `Element.prototype` ([code](https://github.com/salesforce/lwc/blob/131440e43fc5b63e054774df97edb4d25b3021e7/packages/%40lwc/synthetic-shadow/src/faux-shadow/element.ts#L162-L167)). Because `Element` is higher up in the proto-chain than `HTMLElement`, LWC's polyfill is never invoked.

**Comment by sarveshnagpal** [comment]
Thanks @DamonDay and @bakervin for reporting. Thanks @pmdartus for fixing the issue!

**Comment by DamonDay** [comment]
Really appreciate for your efforts!
