### ISSUE TITLE
Access to XMLHttpRequest at 'https://k.clarity.ms/collect' from origin [here url] has been blocked by CORS policy

### ISSUE THREAD

**Issue by ctomczyk** [microsoft/clarity#262]
Going to https://www.sitelint.com/ I see in the console the following issue:

`Access to XMLHttpRequest at 'https://k.clarity.ms/collect' from origin 'https://www.sitelint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

It seems the endpoint https://k.clarity.ms/collect hasn't been configured with the correct headers.

**Comment by ClaritySupport** [comment]
@ctomczyk ,If your website has a CSP, you need to add Clarity to the allowed websites. Otherwise, browsers will block Clarity resources, and the Clarity dashboard's data is affected.
Add Clarity to your default-src directive, which is a future proof way to add Clarity to your CSP, refer [Clarity Content Security Policy](https://learn.microsoft.com/en-us/clarity/clarity-csp) for more details.

**Comment by ctomczyk** [comment]
@ClaritySupport CSP was updated, but not in relation to Clarity. However, seems the issue has been fixed so I will close this ticket. Thank you.
